### PR TITLE
Add Storybook and plop generators

### LINKED ISSUE #12: Add React Storybook
Add support for Storybook in the devtools. Currently we need to build and reload the extension which creates a slow end-to-end workflow. Allow rapid prototyping with Storybook.

### PR DESCRIPTION
**Pull request by tinahollygb**
The current developer workflow is less than ideal, requiring developers to reload the extension in the extension configuration section. 

These changes add Storybook so we can use live reloading. Provided our components don't have any requirements on any Chrome extension API's, this will work. This can be achieved by using presentation-container component architecture and only mounting presentational components in Storybook.

I've added the ChakraProvider so Chakra styles can apply to our own components. Also loaded the global.css stylesheet which appears to be working. I haven't tested the Tailwind support but it seems to build. 

These changes also fix a bug that causes an error to log during development only (for not having a `key` on mapped components).

Closes https://github.com/growthbook/devtools/issues/12

image

It also seems to load up all the Chakra UI components into Storybook by default, which is nice, for reference. This doesn't add any new code to our project, it must be scanning the node_modules for the default Storybook configuration. 

image

### CODE REVIEW

**Review by bttf — COMMENTED** [review]
I'm not sure storybook is the best solution here. The main goal is to improve DX of the app in general (re-instate hot-reloading, which we lost when we switched to a webpack-based build). I would not reach for Storybook here since that is more suited for when we want to focus on optimizing UX flows, building a component library, collaborating with design ...

I think a better solution would be to utilize [webpack-dev-server](https://webpack.js.org/configuration/dev-server/). We can swap out our `yarn dev` script with a command to kick off the dev server. We should then be able to point to `localhost:8080/devtools_panel.html` for example, and work from there as you would a normal react app.

There are two hurdles to accomplish this
1. Mocking out the global `chrome` object - this object and its properties are available within chrome extension context but not in the regular web page context. We'll need to mock these out, probably by detecting the environment (e.g. `NODE_ENV === 'development'`), and mocking the behavior and responses of our various calls to it. This is going to be useful since it will let us test different flows and have direct control over the chrome API in a dev environment.
2. Figuring out how to make the app 'functional' in a dev environment, given the above mock object. The normal devtools app does messaging back and forth between the background script and content script, so we need to mimick that in some way. It might be as easy as just 'if in dev, show everything' but will need to figure that out.

These are good hurdles in a way because once we get over them we gain more power in developing the app - we will have a mocked chrome extension API, and probably a better architecture of the app so that it can be driven by the mocked data (much like how unit tests force you to write better code). Let me know what you think.

**Review by bttf — CHANGES_REQUESTED** [review]
See above comment

**Comment by tinahollygb** [comment]
Thanks for the feedback @bttf. Overall I agree that we do need to be able to host the dev tools panel, the popup, and options pages, but I disagree with blocking this merge, as I think Storybook is a tool that can help us get to those goals faster, as well as get the feature work done we need to get done.

> The main goal is to improve DX of the app in general (re-instate hot-reloading, which we lost when we switched to a webpack-based build)

That's a good goal to have, but that is not the goal of this PR. The goal of this PR is to allow me to build out the new functionality I need to build out, and setting up Storybook is the quickest way to do that. 

I think your concern is valid and we should add that to the issues. It looks like [there's an existing issue open](https://github.com/growthbook/devtools/issues/6) for new architecture, perhaps you can handle that in that ticket since you were working on that. The responsibility of that ticket is changing the build and the architecture, which seems like a great place to handle that.

My goal with this set of changes is so that I can build faster and build the new set of functionality in isolation that I need to build. To quote the Storybook site:

> *Build UI components and pages in isolation*
> Implement components and pages without needing to fuss with data, APIs, or business logic.

You can read more about all the problems Storybook solves: https://storybook.js.org/docs/react/get-started/why-storybook

Allowing us to serve the various parts of the app is a good idea that I 100% agree with, but would require a substantial refactor. Doing so would require us to refactor the app to follow presentational-container component architecture, and Storybook is a tool to help with that.

Adding Storybook does not add to the bundle and it does not get in the way of us being able to eventually be able to serve the dev tools panel, it's an optional server developers can run alongside the real one (which is what I've been doing). It actually helps us in that respect since it gives us a place to build out and test the presentational aspects that don't rely on `chrome`.

I would argue this is a good set of tools that should be merged. Do you feel Storybook can detract from, or take away from or goals, or negatively impact the tooling? If not, I'd recommend merging it and tackling the larger architectural concerns in the future.

**Comment by jdorn** [comment]
I think both Storybook and Webpack dev server are valuable for different things.  Storybook for isolated component UX, Dev server for bigger changes.  So I think we should do both in the long run.

Given the strict deadline for version 2.0 and the visual editor PR, my preference would be to wait to merge this until after the release.

**Comment by bttf** [comment]
This branch has gone stale. Deleting

**Pull request closed without merging**
