### PR TITLE
Update toolbar naming / icons to better match docs

### PR DESCRIPTION
**Pull request by bttf**
Closes https://linear.app/growthbook/issue/GB-101/editor-ui-buttons-and-labels

Screenshot 2023-04-04 at 4 23 53 PM
Screenshot 2023-04-04 at 4 23 46 PM

### CODE REVIEW

**Comment by jdorn** [comment]
While we're changing icons, I think the global styles and custom DOM mutation ones could be clearer as well.

For global styles, maybe use one that has the text "css" in it (e.g. `MdCss`).

For custom DOM mutations, it's such a niche use case, we really only want super advanced technical users who know what they are doing to use it.  That makes it hard to think of a good icon. The current icon, I might click thinking it will let me change copy on the page.  Using something that says "HTML" might make me click it thinking that's how I edit innerHTML of an element.  Almost making me think it shouldn't be one of the 5 options at the top and instead hidden inside the "selection" section as an advanced mode or something.

**Comment by bttf** [comment]
> For custom DOM mutations, it's such a niche use case, we really only want super advanced technical users who know what they are doing to use it. That makes it hard to think of a good icon. The current icon, I might click thinking it will let me change copy on the page. Using something that says "HTML" might make me click it thinking that's how I edit innerHTML of an element. Almost making me think it shouldn't be one of the 5 options at the top and instead hidden inside the "selection" section as an advanced mode or something.

What about moving it to  the 'DOM Changes' tab? Placed under the DOM changes list. It will hint the use-case and show their changes added in real-time

**Comment by jdorn** [comment]
> What about moving it to the 'DOM Changes' tab? Placed under the DOM changes list. It will hint the use-case and show their changes added in real-time

Yeah, that could work.  Basically, put a "Add custom DOM change" CTA beneath the list that shows the form

**Comment by bttf** [comment]
Updated
dom-mutation-add

**Review by jdorn — APPROVED** [review]

**Pull request merged**
